services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_API_URL=${VUE_APP_API_URL:-http://backend:5000}
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=${VUE_APP_API_URL:-http://backend:5000}
    extra_hosts:
      - "backend:host-gateway"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production 